name: Issue Event Workflow

on:
  issues:
    types:
      - opened
      - edited

jobs:
  checkIssue:
    if: ${{ github.event.label.name == 'Published' }}
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue
      run: |
        echo "Issue event triggered"
