name: Issue Event Workflow

on:
  issues:
    types:
      - labeled

jobs:
  checkIssue:
    if: ${{ github.event.label.name == 'published' }}
    runs-on: ubuntu-latest

    steps:
    - name: Check Issue
      run: |
        echo "Issue event triggered"

    - name: Trigger other Workflow
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ secrets.REPO_DEST_TOKEN}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW_ID/dispatches \
        -d '{"ref":"master","inputs":{"title":"タイトル"}}'